[package]
  cjc-version = "0.53.18"
  compile-option = "--dy-std --dy-libs -O2"
  description = "custom iterators collection"
  link-option = ""
  name = "customiterators"
  output-type = "dynamic"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
